# Generated by Django 3.2.1 on 2024-11-11 09:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashaapp1', '0016_alter_diabeteschallengeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressurechallengeimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
