# Generated by Django 3.2.1 on 2024-11-11 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ashaapp1', '0017_alter_bloodpressurechallengeimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otprecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MobileUser',
        ),
        migrations.DeleteModel(
            name='OTPRecord',
        ),
    ]
