# Generated by Django 3.2.1 on 2024-11-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashaapp1', '0019_exercisestreak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseStreak',
        ),
    ]
