# Generated by Django 3.2.1 on 2024-11-20 12:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ashaapp1', '0024_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('Low-Impact Cardio', 'Low-Impact Cardio'), ('Breathing Exercises', 'Breathing Exercises'), ('Flexibility & Stretching', 'Flexibility & Stretching')], max_length=50)),
                ('duration', models.IntegerField(help_text='Exercise duration in minutes')),
                ('feeling_after_exercise', models.CharField(choices=[('great', 'Great (likely BP improvement)'), ('normal', 'Normal (no significant change)'), ('slightly_tired', 'Slightly Tired (potential BP elevation)'), ('dizzy', 'Dizzy or Fatigued (potential BP elevation)')], max_length=50)),
                ('activity_intensity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('stress_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('headache', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('light_headedness', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('palpitations', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('energy_boost', models.IntegerField(help_text='Perceived energy boost (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='exercisestreak',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='exercisestreak',
            name='user',
        ),
        migrations.DeleteModel(
            name='BPExerciseStreak',
        ),
        migrations.DeleteModel(
            name='ExerciseStreak',
        ),
    ]
