# Generated by Django 3.2.1 on 2024-11-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashaapp1', '0025_auto_20241120_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
