# Generated by Django 5.1.4 on 2024-12-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaapp1', '0026_delete_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('nutritionist', 'Nutritionist')], default='user', max_length=20),
        ),
    ]
