# Generated by Django 5.1.4 on 2024-12-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaapp1', '0029_foodanalysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodanalysis',
            options={},
        ),
        migrations.RenameField(
            model_name='foodanalysis',
            old_name='image',
            new_name='food_image',
        ),
        migrations.RemoveField(
            model_name='foodanalysis',
            name='analysis',
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='food_item',
            field=models.CharField(default='apple', max_length=255),
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='servings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='foodanalysis',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foodanalysis',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='foodanalysis',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='foodanalysis',
            name='protein',
            field=models.FloatField(),
        ),
    ]
